---
    version: '3.3'
    
    services:
      database:
        image: postgres:12
        container_name: database
        environment:
          TZ: America/Sao_Paulo
          POSTGRES_PASSWORD: 5df5f458377cc7d25b45dfa8dff77d38
          POSTGRES_USER: master
          POSTGRES_DB: node_api_db
          TERM: xterm-256color
        ports:
          - "5432:5432"
        expose:
          - "5432"
    
